[package]
name = "desktop_logo_core"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
image = { workspace = true }

[dev-dependencies]
image = { workspace = true }
tempfile = "3"